maze.go
maze_test.go
standard.go

Maze mode addresses the following bugs with the previous "snack-a-tron" challenge mode:
[x] New Ruleset so snakes can know they're in this mode
[x] Turn 0: should fill the entire board with food
[x] Turn 1: spawn food in front of snakes
[x] Eliminated snakes backfill with food immediately

New "Maze" Game Mode

---

cli/commands/play.go

Currently, the CLI code has Latency as a uint32, which makes good
sense. However, both the [API reference](https://docs.battlesnake.com/references/api#battlesnake) and the production implementation of the battesnake server use a
decimal integer string to represent Latency instead.
It would be best if both implementations could be switched to use a
numerical value, but changing that in prod would be
backwards-incompatible and may break a bunch of people. It's better
for the behaviors to be consistent, and we can probably change the
simulator without bothering too many folks, so here we are.

Change SnakeResponse.Latency to be a string.

---

cli/commands/play.go

Introduced simple `if` statement when printing the game board with a snake out of bounds. This avoids `panic: runtime error: index out of range [OutOfBondsValue]` exit and finishes the game in desired outcome as `wall-collision` for the snake in question.
I've never written any GOlang before, so if there's easier or more transparent solution, please use that instead :)

fixed panic when printing snake out of bounds

---

cli/commands/play.go

Eliminated snakes will no longer be send in  Snakes part of the payload as the production engine..

Remove Eliminated Snake from the send payload

---

cli/commands/play.go
cli/commands/play_test.go
constrictor_test.go
royale.go
royale_test.go
ruleset.go
standard.go
standard_test.go

This PR refactors the "Royale" ruleset to extract hazard damage out into the "Standard" ruleset. Hazards (AKA sauce) are now stored in the board state, just like food, and the `HazardDamagePerTurn` property on the `StandardRuleset` determines how much to damage snakes that end their turn on top of a hazard square. `RoyaleRuleset` is now just responsible for generating the hazards every turn.
On top of this change, the logic around food and hazards is now slightly different - a snake that ends their turn on a square that contains both food and hazard will be restored to full health (100). Previously, they would end up at 85 health with default settings: -1 for moving, restore to 100, -15 for the hazard.

Refactor RoyaleRuleset and move hazard damage into StandardRuleset

---

cli/commands/play.go
cli/commands/play_test.go
cli/commands/testdata/snake_request_body.json
client/fixtures_test.go
client/models.go
client/models_test.go
client/testdata/snake_request.json
client/testdata/snake_request_empty_ruleset_settings.json
ruleset_test.go
test/test_utils.go

The main idea here is to pull the current types that define the Battlesnake API into this repo, where they can be referenced by the main engine. That way, any changes in the API will automatically be referenced here. Included in those types is the new `customizations` fields on each snake that pass the head, tail, and color.
To actually use that in the CLI in a testable way, I had to refactor things a bit - some of the global state has now been removed, and some confusingly named types and variables have been normalized.
Most of the changes are `Battlesnake` -> `SnakeState` and removing references to a global `Battlesnakes` variable.

DEV 559: Refactor CLI and add customizations

---

.gitignore
cli/commands/output.go
cli/commands/play.go
cli/commands/play_test.go

This PR is the spiritual successor to the following now closed MR: #56.
Following the feedback from the community in the feedback repo [here](https://github.com/BattlesnakeOfficial/feedback/discussions/136) and some conversations on discord, here is a fresh MR which implements exporting of a BS game for further analysis.
The changes are:
* Every line except the last one match the payloads sent by the BS API. The only difference is that for POST /move, the `you` key is always filled with the first snake in the list. The reasoning behind this is documented in the relevant code block.
* The data is saved to memory at each iteration and flushed to file at the end of the game. This enables easier processing since a consumer can wait for the file to exist rather than have to tail the file and …

Add export to file

---

cli/commands/colors.go
cli/commands/play.go

Adds a new flog `-c/--color` to the CLI to use color in the boardview.
Color is disabled by default since not all terminals support the ANSI escape sequences used.

Colored board

---

cli/commands/testdata/snake_request_body.json
client/fixtures_test.go
client/models.go
client/testdata/snake_request.json
client/testdata/snake_request_empty_ruleset_settings.json

Once this update has been pulled into the engine, these new properties will be sent along to all Battlesnakes in the ruleset settings object:
- `hazardMap`
- `hazardMapAuthor`

Add hazardMap and hazardMapAuthor to RulesetSettings

---

cli/commands/play.go

If game ends in a draw, all snakes are eliminated. In that scenario after marshalling to json, the value of `board.snakes` field would be set to `null` instead of `[]`. The bug was introduced in  https://github.com/BattlesnakeOfficial/rules/commit/dabbe7dfb5bd110983569b1ceb0a8098f1bc33b3 .

Fix invalid request to /end when game ended in a draw

---

cli/README.md
cli/commands/play.go

Add turn duration cli option, which specifies minimum turn duration in milliseconds. This enables the user to set a consistent turn step time regardless of the latency of snakes. 
Feature requested by discord user BoldBigflank:
> I would like to delay the game from moving on to the next turn to 500ms every turn, no matter the latency of the snakes
> Because I'm setting up a LED display to show snake games, I want it to be at a set pace

added TurnDuration option to cli

---

cli/README.md

While trying to answer a question from discord, I noticed that the usage and sample output for the CLI is out of date.  I also thought it would be good to highlight different ways of getting JSON output that is better suited to parsing with a script.  Please let me know if this could be worded more clearly!
Changes:
- Update usage section in the README with the latest flags.
- Update default sample output (BoardState fields have changed, OutOfBounds has been removed).
- Add section describing options for getting JSON output with the `--output` and `--debug-requests` flag.

Update CLI documentation

---

board.go
cases_test.go
constrictor.go
constrictor_test.go
pipeline.go
pipeline_internal_test.go
pipeline_test.go
royale.go
royale_test.go
ruleset.go
solo.go
solo_test.go
squad.go
squad_test.go
standard.go
standard_test.go
wrapped.go
wrapped_test.go

This PR adds a new concept called "pipelines" to the rules package. It is intended as a replacement for the "ruleset" concept. While Rulesets are still supported, the internal implementation of them has been re-written to be entirely Pipeline based, so there is no significant reason to continue using them in new code.
A "pipeline" is a series of "stage functions" which are executed in sequence, one after another, in order to modify a game state and produce a next game state. Pipelines can also be executed to initialise a game state and to check if a game has ended. The design of the pipeline system is intended to facilitate easy customization and extension of game modes. Each existing game mode has been broken down into a series of bite-sized logic, called "stages", so that the stages can …

DEV-1096 - add a new "pipeline" concept

---

.github/workflows/release.yml
.github/workflows/test.yml
README.md
cli/README.md
go.mod
go.sum

This upgrades the Go version to 1.18.1, along with making a few minor dependency upgrades to fix incompatibilities.

DEV 1253: Upgrade to Go 1.18.1

---

board.go
board_test.go
cli/README.md
cli/commands/play.go
client/models.go
constrictor_test.go
maps/game_map.go
maps/helpers.go
maps/royale.go
royale.go
royale_test.go
ruleset.go
ruleset_internal_test.go
ruleset_test.go
squad_test.go
standard.go
standard_test.go
wrapped.go
wrapped_test.go

This is a simple maintenance task to convert all the unnecessary `int32` types to `int`.

DEV-1310: change all "int32" types to "int"

---

cli/commands/play.go

I just started building my first snake ([Snattle](https://github.com/MNThomson/Snattle)!), and in trying to link the `cli` for DQLearning I noticed that `isDraw` is always `false`. The output is hard-coded to `false` in `commands/play.go`: https://github.com/BattlesnakeOfficial/rules/blob/1adbc79168a6037e1025c46bc4a8c754de6f0442/cli/commands/play.go#L155-L160
CLI output:
```bash
$ battlesnake play --url http://localhost:8080 --url http://localhost:8000 -W 5 -H 5 -o game.json
...
2022/05/29 16:55:37 [DONE]: Game completed after 3 turns. It was a draw.
2022/05/29 16:55:37 Written 5 lines of output to file: game.json
```
```json
{"winnerId":"","winnerName":"","isDraw":false}
```
```json
{"winnerId":"","winnerName":"","isDraw":true}
```

CLI json output isDraw always false

---

constrictor.go
constrictor_test.go
royale.go
royale_test.go
solo.go
standard.go
wrapped.go

This fixes an edge case where games run through the CLI would sometimes end a turn before the actual end game condition. This looked like the snakes weren't getting their elimination cause set, but the actual issue was that the game was ending early.
Note: the production engine does not use this code path, so games should be unaffected. It only affects the CLI and uses of rules as a library.

DEV-1373: Reorder built-in ruleset stages so that game over is checked first

---

go.mod
go.sum
maps/arcade_maze.go
maps/empty.go
maps/game_map.go
maps/hazards.go
maps/registry_test.go
maps/royale.go
maps/standard.go

Adds a new "Version" field to the GameMap Metadata type. The value is the **current** version of the map. When changes are made, the version number should be incremented by `1`. All versions should start at `1`. The game map registry has a test to ensure that versions are valid.

Add a "Version" field to game maps

---

board.go
board_test.go

Food placement logic is altered such that small boards (7x7 or smaller) that have > 4 snakes will only spawn food in the center. This avoids a possible edge case in the original logic where the food placement for nearby snakes can overlap and throw an error.

allow initial food placement for 8 snakes on 7x7 board

---

board.go
board_test.go
maps/hazards.go
maps/hazards_internal_test.go
maps/hazards_test.go
maps/standard.go

This PR adds fixed snake start positions for the rivers and bridges map.

fix for rivers and bridges snake start positions

---

maps/hazards.go

Updated the map to grow the box every 12 turns instead of every 15 turns

Speeding up DirectionalExpandingBoxMap hazard growth

---

board.go
board_test.go
constrictor_test.go
solo_test.go
standard.go
standard_test.go

This ensures that `snake.EliminatedOnTurn` is set whenever a snake is eliminated. To make it easier to be more consistent, I added a new function called `EliminateSnake` to centralize snake elimination logic and ensure that all three elimination fields are updated.

DEV-1479 ensure snake elimination turn is set

---

cli/commands/play.go

Previously the CLI would exit immediately with an error if a snake returned a response with invalid JSON.
Now the CLI continues running the game and a snake with an bad response continues in the direction of it's last move.
Also logs a warning with details about the invalid response. Where possible, the log includes the response body in case it contains helpful info.
Resolves https://github.com/BattlesnakeOfficial/feedback/discussions/205
Timeout:
```
2022/07/26 10:22:19 [WARN]: Request to http://localhost:5003/move failed
Error: Post "http://localhost:5003/move": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
Bad status code (and non-JSON response)
```
2022/07/26 10:24:12 [WARN]: Got non-ok status code from http://165.227.35.82:5000/move
StatusCode: 502 …
```

fix CLI to handle bad responses

---

maps/healing_pools.go
maps/healing_pools_test.go

Healing pools are now removed one at a time based on the RoyaleSettings.ShrinkEveryNTurns setting

Add decay logic to healing pools

---

cli/README.md
cli/commands/info.go
cli/commands/list.go
cli/commands/map.go
cli/commands/root.go
maps/registry.go
maps/registry_test.go

When a user downloads the binary distribution of the rules cli, it is not apparent as to what the names of the available maps are nor the supported board sizes and snake counts which are allowed for each map without digging into the source code.
This PR adds a new command `map` alongside `play`.
This command provides two subcommands initially:
- `battlesnake map list`
- lists available map names
- `battlesnake map info <map name/id>`
- Displays meta data for a given map including min/max snake count and supported board size
I understand that adding a new _top-level_ cobra command may be undesirable and may require future design discussions. I initially added to the "map not found" output; however, it seemed to fit better into its own command and allows for potential future extension. …

add 'map' cli command to provide map information

---

constants.go
constrictor.go
maps/arcade_maze.go
maps/empty.go
maps/game_map.go
maps/hazards.go
maps/healing_pools.go
maps/registry_test.go
maps/royale.go
maps/sinkholes.go
maps/solo_maze.go
maps/standard.go
ruleset.go
ruleset_test.go

- add support for wrapped_constrictor game mode
- add tags to map metadata

Add wrapped_constrictor game mode and support for map tags

---

cli/commands/info.go
maps/registry.go

Update the `map info` cli command to display map metadata tags.

add tags to map info cli output

---

maps/hazard_pits.go
maps/hazard_pits_test.go

New 4-player map that that lays out a grid-like pattern of squares with pits filled with hazard sauce. Every N turns the pits will fill with another layer of sauce up to a maximum of 4 layers which last a few cycles, then the pits drain and the pattern repeats

Hazard Pits Map

---

maps/rivers_and_bridges.go
maps/rivers_and_bridges_test.go

create two new variations of the map rivers and bridges maps for 11x11 and 19x19 boards with additional hazards along the edge to limit movement in wrapped mode.

New Island and Bridges variations

---

maps/castle_wall.go
maps/castle_wall_test.go
maps/game_map.go
maps/game_map_test.go
maps/hazard_pits.go
maps/registry_test.go
maps/rivers_and_bridges_test.go

Adds a Validate method to Metadata for checking and generating helpful errors when the number of players or map size is invalid, and a bunch of accessor methods to Editor for checking what's on the board already.
The refactoring of existing maps to use these will be in a follow-up ticket.

DEV 1676: Add maps helper functions

---

board.go
maps/helpers.go
maps/helpers_test.go
maps/rivers_and_bridges.go
maps/rivers_and_bridges_test.go

Also refactors these maps to avoid using a temp board state, and moves a few utilities from the top-level package into maps.

DEV-1703: Avoid spawning food on hazards for islands and bridges map

---

cli/commands/output.go
cli/commands/play.go
cli/commands/play_test.go
cli/commands/testdata/jsonl_game.json
cli/commands/testdata/jsonl_game_complete.json
cli/commands/testdata/jsonl_turn_0.json
cli/commands/testdata/jsonl_turn_1.json

This adds some testing for the output JSONL format, and fixes a bug where the final turn (normally sent to `/end`) was not being recorded in the output file.
The latency measured from the CLI is now also recorded in the output file.

DEV 1916: Fix output issues in CLI

---

cli/README.md

After the go 1.17 update the "go get" command is deprecated "go install" is being used instead. and the URL of the git repository was wrong.

README.md modified

---

maps/snail_mode.go

In the fall me and Jonathan worked on an update to the Engine specifically with SnailMode in mind, and refactored SnailMode to use this new `PreUpdate` method
This allowed us to not have to use off-board hazards as state!
However we want to use Snail Mode for our first Community Tournament! And the web engine doesn't support PreUpdate yet, so we are reverting Snail Mode to its old Pre-PreUpdate version :lol:

Revert SnailMode to not use PreUpdate
